@startuml

package sample <<Folder>>{
class Main extends javafx.application.Application
class Controller implements javafx.fxml.Initializable
class Node
package strategy <<Folder>>{
class AddArrow implements Strategy
class ChangePosition implements Strategy
class ChangeSize implements Strategy
interface Strategy
class Context
}
}

@enduml